name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GNU Arm Embedded Toolchain
    # You may pin to the exact commit or the version.
    # uses: ryanwinter/arm-none-eabi-gcc@cd4320c47a50058e479f401604ba28be565e46ac
      uses: ryanwinter/arm-none-eabi-gcc@v2.0.1
    - name: make
      run: make
